version: '2'
services:
  client:
    build: ./
    image: shdkej/template-client:0.1.0
    command: npm start
    volumes:
      - ./:/usr/app
      - /usr/app/node_modules
    ports:
      - "3000:3000"
