# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: npm ci

      - name:  'Automated Version Bump'
        id: tag
        uses:  'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          default: prerelease
          
      - name: check tag output
        run: echo ${{ steps.tag.output.newTag }}

      - name: Generate Auto Changelog
        uses: ahmadawais/action-auto-changelog@master
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
